# Site settings
title: Static
SEOTitle: whvixd | blog
header-img: img/post-bg-maindesk.jpg
email: whvixd@163.com
description: "Fighting ! ! ! The young !"
keyword: "whvixd, Blog, qilixiang, 王志祥, Java , HTML , JavaScript , Python"
url: "http://whvixd.com/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/whvixd/qilixiang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "You have to let us struggle for ourselves, even if we must die in the process. "
sidebar-avatar: /img/avatar-by.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     3283052617/profile?topnav=1&wvr=6&is_all=1
zhihu_username:     qilixiang-41/activities
github_username:    whvixd
# facebook_username:  baiying.qiu.7
jianshu_username:   2bc643a3974e
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
# disqus_username: qiubaiying

# 多说 将于2017年6月1日正式关停服务，建议使用 Disqus（http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241）
# Duoshuo settings
# duoshuo_username: qiubaiying
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
#    {
#       title: "mayun",
#        href: "https://weibo.com/mayun?refer_flag=1001030101_&is_hot=1"
#    },{
#        title: "mahuateng",
#        href: "http://t.qq.com/pony/"
#    },{
#        title: "leijun",
#        href: "https://weibo.com/leijun?refer_flag=1001030101_"
#    },{
#        title: "dongge",
#        href: "https://weibo.com/liuqiangdong?refer_flag=1001030101_&is_hot=1"
#    },
    {
        title: "me",
        href: "https://weibo.com/3283052617/profile?topnav=1&wvr=6&is_all=1"
    }
]
